### ISSUE TITLE
Invalid start-node-id for Pyhgtmap on Windows 11 

### ISSUE THREAD

**Issue by bmffb** [marfrh/osm-map-generator#1]
Using the recommended start-node-id and start-way-id for the pyhgtmap command I get the following error and there is no generation of correct elevation data:
```
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\pyhgtmap.exe\__main__.py", line 7, in <module>
  File "C:\Python39\lib\site-packages\pyhgtmap\main.py", line 66, in main
    main_internal(sys.argv[1:])
  File "C:\Python39\lib\site-packages\pyhgtmap\main.py", line 58, in main_internal
    HgtFilesProcessor(opts.nJobs, opts.startId, opts.startWayId, opts).process_files(
  File "C:\Python39\lib\site-packages\pyhgtmap\hgt\processor.py", line 281, in process_files
    self.process_file(file_name, check_poly)
  File "C:\Python39\lib\site-packages\pyhgtmap\hgt\processor.py", line 239, in process_file
    self.process_tile(file_name, tile)
  File "C:\Python39\lib\site-packages\pyhgtmap\hgt\processor.py", line 212, in process_tile
    self.process_tile_internal(file_name, tile)
  File "C:\Python39\lib\site-packages\pyhgtmap\hgt\processor.py", line 150, in process_tile_internal
    new_start_id, ways = osm_output.write_nodes(
  File "C:\Python39\lib\site-packages\pyhgtmap\output\pbfUtil.py", line 148, in write_nodes
    return next_node_id, pyhgtmap.output.build_efficient_ways(ways)
  File "C:\Python39\lib\site-packages\pyhgtmap\output\__init__.py", line 143, in build_efficient_ways
    return numpy.array(
OverflowError: Python int too large to convert to C long
``` 
Is there a workaround? Up to 10 digits for both ids works fine. But with 11 digits or up the error occurs.

**Comment by marfrh** [comment]
As written in the README, osm-map-generator will only work on Linux.  I do not have the possibility to test things on Windows.
I would have suggested to file an issue at pyhgtmap, but I saw you already opened one there :-)
https://github.com/agrenott/pyhgtmap/issues/7
